version: 2.1
orbs:
  node: circleci/node@3.0.0

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: ssh -oStrictHostKeyChecking=no -v ./build/* $DROPLET_USER@$DROPLET_IP:/var/www/html/

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
