version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-deploy:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: scp -o StrictHostKeyChecking=no -r ./build/* $DROPLET_USER@$DROPLET_IP:/var/www/html/

# Orchestrate our job run sequence
workflows:
  build-and-deploy-project:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - main
